<a href="https://colab.research.google.com/github/SuKay712/LearnPyTorch/blob/main/00_Begin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you a question :https://facebook.com


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi

Thu Sep 14 10:56:43 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensor
torch.Tensor()

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python as Int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7, 8],
                                   [ 2, 10]])
matrix

tensor([[ 7,  8],
        [ 2, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 2, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#tensor
tensor = torch.tensor([ [ [ 1, 2, 3],
                                      [4,5,6],
                                      [7, 8, 9] ],
                                    [ [ 1, 2, 3],
                                      [4,5,6],
                                      [7, 8, 9] ] ])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 3, 3])

In [ ]:
tensor[0,1, 2]

tensor(6)

##random tensors
why random?
bởi vì có rất nhiều mạng nơ ron bắt đầu bằng các tensors với dữ liệu là các số random và sau đó họ điều chỉnh các số đó để biểu diễn data tốt hơn
`bats đầu với một random data -> look at data -> update random numbers -> look at data -> update number

In [ ]:
#tao mot random tensor co size (3, 4)
random_tensor = torch.rand(4, 3, 4)
random_tensor

tensor([[[0.7747, 0.3931, 0.2327, 0.7488],
         [0.5371, 0.2574, 0.8625, 0.1593],
         [0.0456, 0.0766, 0.4236, 0.0144]],

        [[0.8733, 0.6555, 0.6077, 0.1806],
         [0.7573, 0.8937, 0.2420, 0.9810],
         [0.6968, 0.4163, 0.8876, 0.6363]],

        [[0.3161, 0.1790, 0.0132, 0.1379],
         [0.1595, 0.4278, 0.4240, 0.6396],
         [0.7100, 0.9545, 0.7820, 0.3339]],

        [[0.8657, 0.6908, 0.2863, 0.8995],
         [0.6110, 0.8030, 0.7941, 0.2370],
         [0.1367, 0.1540, 0.7614, 0.6470]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#tao mot tensor ngau nhien voi hinh dang giong image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) #height, width, rgb channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#use torch.range()
one_to_hundred = torch.arange(start = 1, end = 100, step = 2)


In [ ]:
#create tensor zeros shape like (input = tensor)
ten_zeroes = torch.zeros_like(input = one_to_hundred)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

##Tensor datatypes



**Note**: Tensor datatypes is one of the 3 big errors you will run into Pytorch & deeplearning:
1. Tensor not right data type
2. Tensor not right shape
3. Tensor not one the right device

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,  6.0,  9.0],
                                                 dtype = None , #what data is the tensor
                                                  device = None, #whate device is your tensor on
                                                  requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([1, 2, 3], dtype = torch.int64)
int_32_tensor

tensor([1, 2, 3])

float_32_tensor * int_32_tensor

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2878, 0.6251, 0.5975, 0.7501],
        [0.1742, 0.3723, 0.6004, 0.9716],
        [0.8604, 0.9741, 0.8886, 0.5862]])

In [ ]:
print(some_tensor.shape, some_tensor.device, some_tensor.dtype)

torch.Size([3, 4]) cpu torch.float32


### Manipulatin Tensor(tensor operation)

1. addtion
2. subtraction
3. multiplication
4. division
5. matrix multiplication

In [ ]:
#addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiply
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
#subtract
tensor = torch.tensor([1, 2, 3])
tensor - 1

tensor([0, 1, 2])

In [ ]:
#try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
#element wise multiply
print(tensor, "*", tensor)
print(f"Equal: {tensor *tensor }")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [ ]:
#matrix multiply
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
#shapes for matrix multiply
tensor_A = torch.tensor([ [1, 2],
                                        [2,  3],
                                         [4, 5]])
tensor_B = torch.tensor([ [1, 2, 3],
                                        [2,  3, 1]])
torch.matmul(tensor_A, tensor_B)

tensor([[ 5,  8,  5],
        [ 8, 13,  9],
        [14, 23, 17]])

In [ ]:
tensor_A.T

tensor([[1, 2, 4],
        [2, 3, 5]])

##Finding the min, max, mean. sum, etc(tensor aggregation)


In [ ]:
#create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean - note: torch.mean() function requires a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

#Finding the positional min and max


In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find min index
x.argmin(), x[0]

(tensor(0), tensor(0))

In [ ]:
#find max index
x.argmax(), x[0]

(tensor(9), tensor(0))

##reshape, stacking, squeezing and unsqueezing tensors
* reshaping - reshapes an input tensor to a defined shape
* view - return a vew of an input tensor of certain shape but keep the same memory as the orginal tensor
* stacking - combine muliple tensors on top of each orther (vstack) or side by side (hstack)
* squeezing - remove all `1` dimension from a tensor
* unsqueezing - add a `1` dimension to a target tensor
* permute - return a view of the input with dimension permute (swapped)  in a certain way

In [ ]:
import torch
x = torch.arange(1. , 10.)
x ,  x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
 #add an extra dimension

 x_reshaped = x.reshape(1, 9)
 x_reshaped.shape, x_reshaped

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change z change x because they has the same memory
z[ :, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other
x_stacked = torch.stack([x,  x,  x,  x,  x], dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#stack tensors on top of each other
x_stacked = torch.vstack((torch.tensor([1,  2,  4,  5]),  torch.tensor([1, 2, 3, 4])))
x_stacked

tensor([[1, 2, 4, 5],
        [1, 2, 3, 4]])

In [ ]:
#stack tensors on top of each other
x_stacked = torch.hstack([x,  x,  x,  x,  x] )
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#torch.squeezing() - remove all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze()- add a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"New tensor:{x_unsqueezed}")
print(f"New Shape:{x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape:torch.Size([1, 9])


In [ ]:
#torch.permute() - rearrange the dimension of a target tensor in a specified order

x_origin = torch.rand(size = (224, 224, 3))  # [height, width, colour_channels]
#permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_origin.permute(2, 0 , 1) # shift axis 0->1, 1-> 2, 2->0
print(f"previous shape:{x_origin.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x_origin[0,0, 0] = 1111111
x_origin[0, 0, 0], x_permuted[0,0,0]

(tensor(1111111.), tensor(1111111.))

##Index (select data from tensor)
similar to numpy

###Pytorch tensors & Numpy
Numpy to Tensor -> `torch.from_numpy(ndarray)`
Tensor to Numpy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #  warning: when converting np to tensor: dtype default = float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor.dtype

torch.float32

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

##Random tensor


In [ ]:
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.0207, 0.2905, 0.2709, 0.2804],
        [0.4196, 0.4440, 0.2614, 0.6400],
        [0.0377, 0.3932, 0.2697, 0.4723]])
tensor([[0.9311, 0.8341, 0.4320, 0.0046],
        [0.8667, 0.3006, 0.4251, 0.5248],
        [0.3103, 0.8535, 0.6228, 0.4793]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 12
torch.manual_seed(RANDOM_SEED)
rand_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_tensor_D = torch.rand(3, 4)
print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##check GPU access
https://pytorch.org/docs/stable/notes/cuda.html#best-practices


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
#count number of devices
torch.cuda.device_count()

1

In [ ]:
#create a tensor (default cpu device)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###Moving tensors back to numpy


In [ ]:
#if tensors is on GPU, it cant convert to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
#to fix that, turn back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

###00. PyTorch Fundamentals Exercises
https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb
